#MENU SCREEN
import tkinter
from tkinter import *
t=tkinter.Tk()
t.title('SECOND FRAME')
t.geometry('1000x1000')
mb=Menu(t)
fm=Menu(mb)
fm.add_command(label='NEW')
fm.add_separator()
fm.add_command(label='OPEN')
fm.add_separator()
fm.add_command(label='SAVE')
fm.add_separator()
fm.add_command(label='EXIT')
fm.add_separator()
mb.add_cascade(label='FILE',menu=fm)
t.config(menu=mb)
fm1=Menu(mb)
fm1.add_command(label='NEW')
fm1.add_separator()
fm1.add_command(label='OPEN')
fm1.add_separator()
fm1.add_command(label='SAVE')
fm1.add_separator()
fm1.add_command(label='EXIT')
fm1.add_separator()
mb.add_cascade(label='EDIT',menu=fm)
t.config(menu=mb)
t.mainloop()